config/routes.rb
PlaylistrrOnRailsV2::Application.routes.draw do

  resources :artists do
    resources :songs do
      resources :genres
    end
  end
  resources :songs
  resources :genres

  get "home/index"
  root :to => 'home#index'

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  attr_accessible :name, :songs
  validates :name, :presence => true
  validates_uniqueness_of :name, :case_sensitive => false
  has_many :songs, :dependent => :destroy
  has_many :genres, :through => :songs

  accepts_nested_attributes_for :songs, :allow_destroy => :true,
    :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }

  def add_songs(songs)
    songs.each do |song_hash|
      s = Song.new
      s.genre = Genre.find_or_create_by_name(song_hash[:genre])
      s.name = song_hash[:name]
      self.add_song(s)
    end
  end

  def songs_count
    songs.size
  end

  def add_song(song)
    songs << song
    song.artist = self
  end
end

app/models/genre.rb
class Genre < ActiveRecord::Base
  attr_accessible :name
  validates :name, :presence => true
  has_many :songs
end

app/models/song.rb
require 'oembed'

class Song < ActiveRecord::Base
  attr_accessible :name, :artist_id, :genre_id
  belongs_to :artist
  belongs_to :genre

  # def youtube
  #   YoutubeSearch.search("#{self.artist.name} #{self.name}").first
  # end

  def self.new_from_params(params)
    self.new.tap do |s|
      s.name = params[:song_name]
      s.genre = Genre.find_or_create_by_name(params[:genre_name])
      Artist.find_or_create_by_name(params[:artist_name]).add_song(s)
    end
  end

  def genre=(genre)
    @genre = genre
    genre.songs << self
  end

  def youtube_url
    id = YoutubeSearch.search("#{self.artist.name} - #{self.name}").first["video_id"]
    url = "http://www.youtube.com/watch?v=#{id}"
  end

  def embedcode
    OEmbed::Providers::Youtube.get(self.youtube_url).html
  end
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @artists }
    end
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
    @artist = Artist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/new
  # GET /artists/new.json
  def new
    @artist = Artist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @artist }
    end
  end

  # GET /artists/1/edit
  def edit
    @artist = Artist.find(params[:id])
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(params[:artist])
    @artist.add_songs(params[:songs])

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render json: @artist, status: :created, location: @artist }
      else
        format.html { render action: "new" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /artists/1
  # PUT /artists/1.json
  def update
    @artist = Artist.find(params[:id])

    respond_to do |format|
      if @artist.update_attributes(params[:artist])
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy

    respond_to do |format|
      format.html { redirect_to artists_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
 
  def index
    @genres = Genre.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @genres }
    end
  end  

  def create
    @artist = Artist.find(params[:artist_id])
    @genre = @artist.genres.create(params[:genre])
    redirect_to artist_path(@artist)
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    @genres = @artist.genres.find(params[:id])
    @genres.destroy
    redirect_to artist_path(@artist)
  end

  def show
    # @artist = Artist.find(params[:id])
    # @genres = @artist.genres.find(params[:id])
    @genre = Genre.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    @songs = Song.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @songs }
    end
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.create(params[:song])
    redirect_to artist_path(@artist)
  end


  def destroy
    @artist = Artist.find(params[:artist_id])
    @songs = @artist.songs.find(params[:id])
    @songs.destroy
    redirect_to artist_path(@artist)
  end

  def show
    # @artist = Artist.find(params[:id])
    # @songs = @artist.songs.find(params[:id])
    @song = Song.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @artist }
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for(@artist) do |f| %>
  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <fieldset>
    <p>
      <label>Song Name: </label> <input type="text" name="songs[][name]" />
    </p>

    <p>
      <label>Genre Name: </label> <input type="text" name="songs[][genre]" />
    </p>
  </fieldset>

    <%= f.submit %>

<% end %>

app/views/artists/edit.html.erb
<p><a href="/"><< home</a></p>

<h1>Editing artist</h1>

<%= render 'form' %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>ARTISTS</h1>

<table>
<% @artists.sort { |a,b| a.name <=> b.name }.each do |artist| %>
  <tr>
    <td><b><%= link_to artist.name, artist %></b>&nbsp;</td>

  </tr>
<% end %>
</table>

app/views/artists/new.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>New artist</h1>

<%= render 'form' %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<p>Artist:</p>
  <h1><%= @artist.name %></h1>


<ul style="list-style-type: none;">
  <p>
    Song list: 
  </p>
    <b><%= render @artist.songs %></b>
</ul>
<br/>

<%= link_to '<< Back', artists_path %>

app/views/genres/edit.html.erb
<h1>Edit Genres</h1>

app/views/genres/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>GENRES</h1>

<table> 


  <% @genres.each do |genre| %> 
  <tr>
    <td><b><%= link_to genre.name, genre %></b></td>
  </tr>
<% end %>
</table>

app/views/genres/new.html.erb
<h1>New Genres</h1>

app/views/genres/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<p>Genre:</p>
  <h1><%= @genre.name %></h1>

<ul style="list-style-type: none;">
  <p>
    Songs: 
  </p>
    <b><%= render @genre.songs %></b>
</ul>

<%= link_to '<< Back', genres_path %> 

app/views/home/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>Playlistrrr</h1>

<h3>Share music with anyone, anywhere.</h3> 
<ul>
  <li>Easily find your favorite music.</li>
  <li>Search by <%= link_to "ARTIST", artists_path %>, <%= link_to "SONG", songs_path %> or  <%= link_to "GENRE", genres_path %>.</li>
  <li>Create and share playlists with ANYONE, no need to sign-up or download a thing.</li>
</ul>
<br/>
<p><strong><< <%= link_to "ARTISTS", artists_path %> >> | << <%= link_to "SONG", songs_path %> >> | << <%= link_to "GENRE", genres_path %> >></strong></p>
<br/>
<< <%= link_to 'Add a Song', new_song_path %> >> << <%= link_to 'Add an Artist', new_artist_path %> >>



<br/>
<h4>About Playlistrrr</h4>
<p>Spotify, Rdio, and iTunes won't let you share music with non-members. That's lame.</p>
<p>Playlistrrr lets you share music with just a simple, permanent link. The music is streamed via the YouTube open API.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlaylistrrOnRailsV2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="background: #6EFF70;">
<%= link_to 'home', root_path %> | <%= link_to 'artists', artists_path %> | <%= link_to 'songs', songs_path %> | <%= link_to 'genres', genres_path %>
<br/>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<!-- This code doesn't work -->

<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <fieldset>
    <p>
      <label>Artist Name: </label> <input type="text" name="artist[name]" />
    </p>

    <p>
      <label>Genre Name: </label> <input type="text" name="songs[][genre]" />
    </p>
  </fieldset>

    <%= f.submit %>

<% end %>

app/views/songs/_song.html.erb
<!-- used for rendering the individual artist's page -->
<li><h2><%= song.name %></h2></li>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

app/views/songs/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>SONGS</h1>
<table> 

  <% @songs.each do  |song| %> 
  <tr>
    <td><b><%= link_to song.name, song %></b>&nbsp;</td>
    <td>by &nbsp;<b><%= song.artist.name %></b>&nbsp;</td>

  </tr>
<% end %>

</table>
<br/>

app/views/songs/new.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1>Add a Song</h1>

<fieldset>
  <%= render "songs/form" %>
</fieldset>

app/views/songs/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p> <% end %>

<h1><%= @song.name %></h1>


<%= raw @song.embedcode %>
<br/>
<%= link_to '<< Back', songs_path %>